import { describe, it, expect } from 'vitest';
import { ChecklistMarkdownFormatter } from '../../src/interfaces/cli/ChecklistMarkdownFormatter.js';
import { ChecklistItemDTO } from '../../src/application/use-cases/GeneratePRChecklistUseCase.js';

describe('ChecklistMarkdownFormatter', () => {
  const formatter = new ChecklistMarkdownFormatter();

  describe('format', () => {
    it('should include comment marker', () => {
      const result = {
        checklist: [],
        summary: ''
      };

      const output = formatter.format(result);

      expect(output).toContain('<!-- review-dojo-checklist -->');
    });

    it('should format empty result correctly', () => {
      const result = {
        checklist: [],
        summary: ''
      };

      const output = formatter.format(result);

      expect(output).toContain('## :clipboard: Review Knowledge Checklist');
      expect(output).toContain('No relevant knowledge items found');
      expect(output).toContain('Generated by [review-dojo]');
    });

    it('should format items by severity', () => {
      const items: ChecklistItemDTO[] = [
        {
          category: 'security',
          severity: 'critical',
          title: 'SQLインジェクション対策',
          checkItem: 'SQLインジェクション対策を実施しましたか？',
          knowledgeId: 'security/java/sqlインジェクション対策'
        },
        {
          category: 'performance',
          severity: 'warning',
          title: 'N+1問題',
          checkItem: 'N+1問題を確認しましたか？',
          knowledgeId: 'performance/java/n1問題'
        },
        {
          category: 'readability',
          severity: 'info',
          title: '命名規則',
          checkItem: '命名規則を確認しましたか？',
          knowledgeId: 'readability/java/命名規則'
        }
      ];

      const result = {
        checklist: items,
        summary: '対象言語: java | チェック項目数: 3件 | 重要: 1件 | 警告: 1件 | 情報: 1件'
      };

      const output = formatter.format(result);

      // Should have severity sections in order
      expect(output).toContain('### :rotating_light: Critical');
      expect(output).toContain('### :warning: Warning');
      expect(output).toContain('### :information_source: Info');

      // Should include all items
      expect(output).toContain('SQLインジェクション対策');
      expect(output).toContain('N+1問題');
      expect(output).toContain('命名規則');

      // Should include summary
      expect(output).toContain(result.summary);
    });

    it('should format details with category and knowledge ID', () => {
      const items: ChecklistItemDTO[] = [
        {
          category: 'security',
          severity: 'critical',
          title: 'SQLインジェクション対策',
          checkItem: 'SQLインジェクション対策を実施しましたか？',
          knowledgeId: 'security/java/sqlインジェクション対策'
        }
      ];

      const result = {
        checklist: items,
        summary: '対象言語: java | チェック項目数: 1件'
      };

      const output = formatter.format(result);

      // Should include details in collapsible section
      expect(output).toContain('<details>');
      expect(output).toContain('<summary>Details</summary>');
      expect(output).toContain('**Category**: security');
      expect(output).toContain('**Knowledge ID**: `security/java/sqlインジェクション対策`');
    });

    it('should include checkbox for each item', () => {
      const items: ChecklistItemDTO[] = [
        {
          category: 'security',
          severity: 'critical',
          title: 'SQLインジェクション対策',
          checkItem: 'SQLインジェクション対策を実施しましたか？',
          knowledgeId: 'security/java/sqlインジェクション対策'
        }
      ];

      const result = {
        checklist: items,
        summary: '対象言語: java | チェック項目数: 1件'
      };

      const output = formatter.format(result);

      expect(output).toContain('- [ ] SQLインジェクション対策を実施しましたか？');
    });

    it('should include footer with timestamp', () => {
      const result = {
        checklist: [],
        summary: ''
      };

      const output = formatter.format(result);

      expect(output).toMatch(/Generated by \[review-dojo\]/);
      expect(output).toMatch(/Last updated: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
    });

    it('should group critical items before warning items', () => {
      const items: ChecklistItemDTO[] = [
        {
          category: 'performance',
          severity: 'warning',
          title: 'Warning Item',
          checkItem: 'Warning?',
          knowledgeId: 'perf/warning'
        },
        {
          category: 'security',
          severity: 'critical',
          title: 'Critical Item',
          checkItem: 'Critical?',
          knowledgeId: 'security/critical'
        }
      ];

      const result = {
        checklist: items,
        summary: ''
      };

      const output = formatter.format(result);

      const criticalIndex = output.indexOf('### :rotating_light: Critical');
      const warningIndex = output.indexOf('### :warning: Warning');

      expect(criticalIndex).toBeLessThan(warningIndex);
    });
  });
});
